In [8]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt
import statistics

#Data Loading
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Cleanup Data /converting it into datetime format
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

'[WinError 10054] An existing connection was forcibly closed by the remote host' thrown while requesting HEAD https://huggingface.co/datasets/lukebarousse/data_jobs/resolve/ed776e5a0a8c40ea9d5efbd800772ae52e140f3e/data_jobs.py
Retrying in 1s [Retry 1/5].
Using the latest cached version of the dataset since lukebarousse/data_jobs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at C:\Users\Pradi\.cache\huggingface\datasets\lukebarousse___data_jobs\default\0.0.0\ed776e5a0a8c40ea9d5efbd800772ae52e140f3e (last modified on Sat Jun 13 17:04:48 2026).

In [ ]:
df.loc[0:10, 'salary_rate': 'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [14]:
median_salary_year = df['salary_year_avg'].median()
median_salary_year

np.float64(115000.0)

In [ ]:
median_salary_hour = df['salary_hour_avg'].median()

In [13]:
df_filled= df
df_filled['salary_year_avg'].fillna(median_salary_year)

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [23]:
df['salary_year_avg'] =df_filled['salary_year_avg'].fillna(median_salary_year)
df['salary_hour_avg'] =df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [24]:
df.loc[:10,'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [32]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates()
print('Length of original df is:        ', len(df_filled))
print('Length of drop duplicates df is:', len(df_unique))
print('Rows dropped is:       ', len(df_filled) - len(df_unique))

Length of original df is:         785741
Length of drop duplicates df is: 785640
Rows dropped is:        101

In [33]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])
print('Length of original df is:        ', len(df_filled))
print('Length of drop duplicates df is:', len(df_unique))
print('Rows dropped is:       ', len(df_filled) - len(df_unique))

Length of original df is:         785741
Length of drop duplicates df is: 508042
Rows dropped is:        277699

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [9]:
df['salary_rate'].median()

TypeError: Cannot perform reduction 'median' with string dtype