In [3]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#Data Loading
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Cleanup Data /converting it into datetime format
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [5]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [8]:
df.sample(6)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
648590,Data Scientist,Científico de Datos/ Data Scientist,"Lima, Peru",via BeBee,Full-time,False,Peru,2023-10-11 12:11:57,False,False,Peru,NaN,NaN,NaN,Emprego,"['sql', 'python', 'r', 'sql server', 'oracle',...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
25577,Data Analyst,M-Tech Data Analyst. Job in Edinburgh My Valle...,"Edinburgh, UK",via My Valley Jobs Today,Full-time,False,United Kingdom,2023-01-24 13:16:49,True,False,United Kingdom,NaN,NaN,NaN,Aviagen UK Ltd,['excel'],{'analyst_tools': ['excel']}
306413,Data Engineer,data engineer advanced,"Centenario, Neuquen, Argentina",via BeBee,Full-time,False,Argentina,2023-03-02 17:42:10,False,False,Argentina,NaN,NaN,NaN,BCP,"['python', 'sql', 'nosql', 'sql server', 'orac...","{'async': ['jira'], 'cloud': ['oracle'], 'data..."
667134,Data Scientist,Data Scientist,"Paris, France",via LinkedIn,Internship,False,France,2023-01-10 10:29:34,False,False,France,NaN,NaN,NaN,MEGA International,"['python', 'azure']","{'cloud': ['azure'], 'programming': ['python']}"
121456,Data Engineer,Gis Data Engineer Ii,"Guanajuato, Mexico",via BeBee,Full-time,False,Mexico,2023-10-05 08:17:28,False,False,Mexico,NaN,NaN,NaN,HERE Technologies,"['python', 'sql', 'flow']","{'other': ['flow'], 'programming': ['python', ..."
367832,Senior Data Engineer,Senior Data Migration Technical Engineer/Lead,"Johannesburg, South Africa",via Energy Jobline,Full-time,False,South Africa,2023-07-17 23:56:28,True,False,South Africa,NaN,NaN,NaN,H2R Africa,['azure'],{'cloud': ['azure']}

Copy() method

In [9]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [10]:
df_altered = df_original

In [11]:
df_altered.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [12]:
median_salary = df_altered['salary_year_avg'].median()
median_salary

np.float64(115000.0)

In [13]:
df_altered['salary_year_avg']= df_altered['salary_year_avg'].fillna(median_salary)
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [14]:
df_original.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [15]:
id(df_original)

2143648545104

In [16]:
id(df_altered)

2143648545104

In [17]:
id(df_original) == id(df_altered)

True

now using copy method to solve this issue

In [18]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [19]:
df_altered = df_original.copy()

In [20]:
print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                2143648537200
ID of df_altered:                 2143648535072
Are the two dataframes the same?  False

In [21]:
median_salary = df_altered['salary_year_avg'].median()
df_altered['salary_year_avg']= df_altered['salary_year_avg'].fillna(median_salary)
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [23]:
df_original.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64